development:
  adapter: postgresql
  encoding: unicode
  database: valentine_development
  pool: 5
  username: <%= ENV['USER'] %>
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: valentine_test
  pool: 5
  username: <%= ENV['USER'] %>
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: valentine_production
  pool: 5
  username: <%= ENV['USER'] %>
  host: localhost
  port: 5432